title: Collage Hacks
description: HTML examples and notes
remote_theme: just-the-docs/just-the-docs@v0.8.2
plugins:
  - jekyll-remote-theme

search_enabled: true
color_scheme: dark
# logo: # e.g., /assets/logo.png
aux_links:
  Repo on GitHub:
    - https://github.com/c0d3h01/collage_hacks
